import { and, desc, eq, gte, inArray, lt, ne, sql } from 'drizzle-orm';
import { getDb } from '@/db/client';
import { agentRuns, customers, orderEvents, orderLines, orders, products, serviceMessages } from '@/db/schema';
import { listInvoices } from '@/lib/accounting/invoices';
import { persistFindings } from '@/lib/agents/runner';
import { DESK_AGENTS, type DeskAgentId, type Finding } from '@/lib/agents/types';
import { classifyIntent, extractOrderNumber, isAutoGenerated, parseOrderText, type Intent, type ParsedOrder } from './parse';
import { chooseShipping, creditHoldReason, decideReply, matchProduct, orderIssues, stockShortages, type StockLine } from './policy';
import { cancelOrder, logEvent, toOrderView } from './actions';
import { autoSendEnabled, companyName, sendCustomerMail } from './notify';
import { llmEnabled, readMessageWithLlm, readOrderWithLlm, type LlmClient } from './llm';

const DAY = 86_400_000;
const STUCK_MS = 10 * 60_000;

export interface DeskRunSummary {
  agent: DeskAgentId;
  handled: number;
  error?: string;
}

interface Deps {
  now: Date;
  llm?: LlmClient;
  useLlm: boolean;
}

// ---- Order Intake ---------------------------------------------------------

async function runIntake(d: Deps): Promise<number> {
  const db = getDb();
  const queue = await db.select().from(orders).where(eq(orders.status, 'received'));
  const catalog = await db.select({ id: products.id, name: products.name, unitPrice: products.unitPrice }).from(products).where(eq(products.active, true));
  const allCustomers = await db.select({ id: customers.id, email: customers.email }).from(customers);
  let handled = 0;

  for (const o of queue) {
    // Claim the order so two overlapping runs never parse it twice.
    const claimed = await db.update(orders).set({ status: 'parsing', updatedAt: new Date() }).where(and(eq(orders.id, o.id), eq(orders.status, 'received'))).returning({ id: orders.id });
    if (!claimed.length) continue;

    let lines = await db.select().from(orderLines).where(eq(orderLines.orderId, o.id));
    let parsed: ParsedOrder = { lines: [], shipTo: {} };
    let source = 'structured';
    if (!lines.length && o.rawText) {
      const viaLlm = d.useLlm ? await readOrderWithLlm(o.rawText, d.llm) : null;
      parsed = viaLlm ?? parseOrderText(o.rawText);
      source = viaLlm ? 'ai' : 'rules';
    }

    const email = o.customerEmail ?? parsed.email ?? null;
    const ship = {
      line1: o.shipLine1 ?? parsed.shipTo.line1 ?? null,
      city: o.shipCity ?? parsed.shipTo.city ?? null,
      region: o.shipRegion ?? parsed.shipTo.region ?? null,
      postal: o.shipPostal ?? parsed.shipTo.postal ?? null,
      country: o.shipCountry ?? parsed.shipTo.country ?? null,
    };

    if (!lines.length && parsed.lines.length) {
      lines = await db
        .insert(orderLines)
        .values(parsed.lines.map((l) => ({ orderId: o.id, sku: l.sku ?? null, description: l.description, quantity: l.quantity })))
        .returning();
    }

    const matched = lines.map((l) => ({ line: l, product: matchProduct(l.description, l.sku ?? undefined, catalog) }));
    for (const m of matched) {
      if (m.product) {
        const price = m.line.unitPrice ?? m.product.unitPrice;
        await db.update(orderLines).set({ productId: m.product.id, unitPrice: price }).where(eq(orderLines.id, m.line.id));
        m.line.unitPrice = price;
      }
    }

    // Same sender, same items, within a day: probably sent twice.
    let duplicate = false;
    if (email) {
      const signature = (ls: { description: string; quantity: number }[]) => ls.map((l) => `${l.description.toLowerCase()}:${l.quantity}`).sort().join('|');
      const mine = signature(lines);
      const recent = await db.select().from(orders).where(and(eq(orders.customerEmail, email), ne(orders.id, o.id), ne(orders.status, 'cancelled'), gte(orders.createdAt, new Date(d.now.getTime() - DAY))));
      for (const r of recent) {
        const theirs = await db.select().from(orderLines).where(eq(orderLines.orderId, r.id));
        if (theirs.length && signature(theirs) === mine) duplicate = true;
      }
    }

    const issues = orderIssues({
      lines: matched.map((m) => ({ description: m.line.description, quantity: m.line.quantity, matched: !!m.product })),
      shipTo: ship,
      duplicate,
    });
    const total = matched.reduce((t, m) => t + (m.line.unitPrice ? Number(m.line.unitPrice) * m.line.quantity : 0), 0);
    const customerId = email ? (allCustomers.find((c) => c.email?.toLowerCase() === email)?.id ?? null) : null;
    const status = issues.length ? 'needs_review' : 'confirmed';

    await db
      .update(orders)
      .set({
        status,
        customerEmail: email,
        customerName: o.customerName ?? parsed.customerName ?? null,
        poNumber: o.poNumber ?? parsed.poNumber ?? null,
        customerId,
        shipLine1: ship.line1,
        shipCity: ship.city,
        shipRegion: ship.region,
        shipPostal: ship.postal,
        shipCountry: ship.country,
        total: total ? total.toFixed(2) : null,
        holdReason: issues.length ? issues.join(' ') : null,
        updatedAt: new Date(),
      })
      .where(eq(orders.id, o.id));
    await logEvent({ orderId: o.id, agent: 'order-intake', action: status === 'confirmed' ? 'confirmed' : 'needs_review', detail: `read by ${source}${issues.length ? `: ${issues.join(' ')}` : `, ${lines.length} line(s)`}` });

    if (status === 'confirmed' && email) {
      const body = lines.map((l) => `  ${l.quantity} x ${l.description}`).join('\n');
      const result = await sendCustomerMail(
        email,
        `We received your order ${o.orderNumber}`,
        `Hello,\n\nThanks for your order ${o.orderNumber}. Here is what we have:\n\n${body}\n\nShip to: ${[ship.line1, ship.city, ship.region, ship.postal].filter(Boolean).join(', ')}\n\nWe will email you again when it ships.\n\nKind regards,\n${companyName()}`,
      );
      await logEvent({ orderId: o.id, agent: 'order-intake', action: result.ok ? 'confirmation_sent' : 'confirmation_not_sent', detail: result.ok ? undefined : result.reason });
    }
    handled += 1;
  }
  return handled;
}

// ---- Customer Service -----------------------------------------------------

async function runService(d: Deps): Promise<number> {
  const db = getDb();
  const queue = await db.select().from(serviceMessages).where(eq(serviceMessages.status, 'open')).orderBy(serviceMessages.createdAt);
  let handled = 0;

  for (const m of queue) {
    const claimed = await db.update(serviceMessages).set({ status: 'handling', updatedAt: new Date() }).where(and(eq(serviceMessages.id, m.id), eq(serviceMessages.status, 'open'))).returning({ id: serviceMessages.id });
    if (!claimed.length) continue;

    if (isAutoGenerated(m.fromEmail, m.subject, m.body)) {
      await db.update(serviceMessages).set({ status: 'closed', handledBy: 'agent', escalationReason: 'Automatic mail, no reply sent.', updatedAt: new Date() }).where(eq(serviceMessages.id, m.id));
      await logEvent({ messageId: m.id, agent: 'customer-service', action: 'ignored_automatic_mail' });
      handled += 1;
      continue;
    }

    // What are they asking? Rules always run; the model can refine, but a complaint found by rules is never downgraded.
    const rules = classifyIntent(m.subject, m.body);
    const text = `${m.subject ?? ''}\n${m.body}`;
    const ai = d.useLlm ? await readMessageWithLlm(m.subject, m.body, d.llm) : null;
    const intent: Intent = rules.intent === 'complaint' ? 'complaint' : (ai?.intent ?? rules.intent);

    // Which order? An order number they wrote, else their most recent order.
    let order: typeof orders.$inferSelect | undefined;
    const number = extractOrderNumber(text) ?? ai?.orderNumber;
    if (number) [order] = await db.select().from(orders).where(eq(orders.orderNumber, number));
    if (!order) [order] = await db.select().from(orders).where(eq(orders.customerEmail, m.fromEmail)).orderBy(desc(orders.createdAt)).limit(1);

    const [{ n }] = await db
      .select({ n: sql<number>`cast(count(*) as int)` })
      .from(serviceMessages)
      .where(and(eq(serviceMessages.fromEmail, m.fromEmail), eq(serviceMessages.handledBy, 'agent'), eq(serviceMessages.status, 'auto_replied'), gte(serviceMessages.repliedAt, new Date(d.now.getTime() - DAY))));

    let decision = decideReply({
      intent,
      order: order ? toOrderView(order) : null,
      senderEmail: m.fromEmail,
      now: d.now,
      recentAutoReplies: n,
      company: companyName(),
      newAddress: ai?.newAddress,
    });
    if (decision.mode === 'auto' && !autoSendEnabled()) {
      decision = { ...decision, mode: 'approval', effect: undefined, reason: 'Automatic replies are switched off (DESK_AUTO_SEND=off).' };
    }

    let status: 'auto_replied' | 'awaiting_approval' | 'escalated' = decision.mode === 'auto' ? 'auto_replied' : decision.mode === 'approval' ? 'awaiting_approval' : 'escalated';
    let reason = decision.reason ?? null;
    let repliedAt: Date | null = null;

    if (decision.effect === 'cancel' && order) {
      try {
        await cancelOrder(order.id, 'customer-service', 'Cancelled at the customer\'s request by email.');
      } catch (err) {
        status = 'awaiting_approval';
        reason = err instanceof Error ? err.message : 'Could not cancel the order.';
        decision = { ...decision, effect: undefined };
      }
    }
    if (status === 'auto_replied') {
      const result = await sendCustomerMail(m.fromEmail, m.subject?.toLowerCase().startsWith('re:') ? m.subject : `Re: ${m.subject ?? 'your message'}`, decision.reply);
      if (result.ok) repliedAt = new Date();
      else {
        status = 'awaiting_approval';
        reason = `The reply was ready but could not be sent: ${result.reason}`;
      }
    }

    await db
      .update(serviceMessages)
      .set({ orderId: order?.id ?? null, intent, status, replyDraft: decision.reply, repliedAt, handledBy: status === 'auto_replied' ? 'agent' : null, escalationReason: reason, updatedAt: new Date() })
      .where(eq(serviceMessages.id, m.id));
    await logEvent({
      orderId: order?.id,
      messageId: m.id,
      agent: 'customer-service',
      action: status === 'auto_replied' ? 'auto_replied' : status === 'escalated' ? 'escalated' : 'draft_ready',
      detail: `${intent}${ai ? ' (ai)' : ''}${decision.effect === 'cancel' ? ', order cancelled' : ''}${reason ? `: ${reason}` : ''}`,
    });
    handled += 1;
  }
  return handled;
}

// ---- Order Processing -----------------------------------------------------

async function runProcessing(d: Deps): Promise<number> {
  const db = getDb();
  const invoices = await listInvoices();
  let handled = 0;

  await db.transaction(async (tx) => {
    // SKIP LOCKED: an overlapping run leaves these rows to whoever holds them.
    const queue = await tx.select().from(orders).where(inArray(orders.status, ['confirmed', 'on_hold'])).for('update', { skipLocked: true });

    for (const o of queue) {
      const lines = await tx.select().from(orderLines).where(eq(orderLines.orderId, o.id));
      const overdue = o.customerId
        ? invoices.filter((i) => i.CustomerRef.value === o.customerId).map((i) => ({ balance: i.Balance, dueDate: i.DueDate ?? null }))
        : [];
      const credit = creditHoldReason(overdue, d.now);

      const ids = [...new Set(lines.map((l) => l.productId).filter((x): x is string => !!x))];
      const prods = ids.length ? await tx.select().from(products).where(inArray(products.id, ids)) : [];
      const byId = new Map(prods.map((p) => [p.id, p]));

      // Total needed per stock-tracked product, so two lines of one item are checked together.
      const need = new Map<string, number>();
      for (const l of lines) {
        const p = l.productId ? byId.get(l.productId) : undefined;
        if (p && p.type === 'Inventory' && p.qtyOnHand !== null) need.set(p.id, (need.get(p.id) ?? 0) + l.quantity);
      }
      const stockLines: StockLine[] = [...need].map(([id, qty]) => ({ description: byId.get(id)!.name, quantity: qty, onHand: Number(byId.get(id)!.qtyOnHand) }));
      const shortages = stockShortages(stockLines);

      const holdReason = credit ?? (shortages.length ? `Backorder: ${shortages.map((s) => `${s.description} short by ${s.short}`).join('; ')}` : null);

      if (holdReason) {
        if (o.status !== 'on_hold' || o.holdReason !== holdReason) {
          await tx.update(orders).set({ status: 'on_hold', holdReason, updatedAt: new Date() }).where(eq(orders.id, o.id));
          await tx.insert(orderEvents).values({ orderId: o.id, agent: 'order-processing', action: 'on_hold', detail: holdReason });
          handled += 1;
        }
        continue;
      }

      // Reserve stock. A savepoint keeps one failed order from undoing the others.
      try {
        await tx.transaction(async (sp) => {
          for (const [pid, qty] of need) {
            const got = await sp
              .update(products)
              .set({ qtyOnHand: sql`${products.qtyOnHand} - ${qty}` })
              .where(and(eq(products.id, pid), gte(products.qtyOnHand, String(qty))))
              .returning({ id: products.id });
            if (!got.length) throw new Error('stock changed');
          }
          for (const l of lines) {
            if (l.productId && need.has(l.productId)) await sp.update(orderLines).set({ reservedQty: l.quantity }).where(eq(orderLines.id, l.id));
          }
          await sp.update(orders).set({ status: 'processing', holdReason: null, updatedAt: new Date() }).where(eq(orders.id, o.id));
          await sp.insert(orderEvents).values({ orderId: o.id, agent: 'order-processing', action: 'stock_reserved', detail: `${need.size} tracked item(s)` });
        });
        handled += 1;
      } catch {
        // Someone else took the stock between the check and the update. Try again next run.
      }
    }
  });
  return handled;
}

// ---- Shipping Processing --------------------------------------------------

async function runShipping(d: Deps): Promise<number> {
  const db = getDb();
  let handled = 0;
  await db.transaction(async (tx) => {
    const queue = await tx.select().from(orders).where(eq(orders.status, 'processing')).for('update', { skipLocked: true });
    for (const o of queue) {
      const s = chooseShipping(o.shipCountry, d.now);
      await tx.update(orders).set({ status: 'ready_to_ship', shippingMethod: s.method, shipByDate: s.shipBy, updatedAt: new Date() }).where(eq(orders.id, o.id));
      await tx.insert(orderEvents).values({ orderId: o.id, agent: 'shipping-processing', action: 'ready_to_ship', detail: `${s.method}, ship by ${s.shipBy}${s.international ? ', international: customs documents needed' : ''}` });
      handled += 1;
    }
  });
  return handled;
}

// ---- Findings the desk cannot clear on its own ----------------------------

export async function deskFindings(now: Date): Promise<Record<DeskAgentId, Finding[]>> {
  const db = getDb();
  const [open, msgs] = await Promise.all([
    db.select().from(orders).where(inArray(orders.status, ['needs_review', 'on_hold', 'ready_to_ship', 'shipped'])),
    db.select().from(serviceMessages).where(inArray(serviceMessages.status, ['awaiting_approval', 'escalated'])),
  ]);
  const out: Record<DeskAgentId, Finding[]> = { 'order-intake': [], 'customer-service': [], 'order-processing': [], 'shipping-processing': [] };
  const link = { type: 'link', href: '/dashboard/orders' };

  for (const o of open) {
    if (o.status === 'needs_review') {
      out['order-intake'].push({ agent: 'order-intake', severity: 'medium', dedupeKey: `desk:review:${o.id}`, title: `${o.orderNumber} needs a person to check it`, detail: o.holdReason ?? 'Flagged by intake.', action: link });
    } else if (o.status === 'on_hold') {
      const days = Math.floor((now.getTime() - o.updatedAt.getTime()) / DAY);
      out['order-processing'].push({ agent: 'order-processing', severity: days >= 3 ? 'high' : 'medium', dedupeKey: `desk:hold:${o.id}`, title: `${o.orderNumber} is on hold`, detail: o.holdReason ?? 'On hold.', action: link });
    } else if (o.status === 'ready_to_ship') {
      if (o.shipByDate && new Date(`${o.shipByDate}T00:00:00Z`).getTime() < now.getTime() - DAY / 2) {
        out['shipping-processing'].push({ agent: 'shipping-processing', severity: 'high', dedupeKey: `desk:late:${o.id}`, title: `${o.orderNumber} is past its ship-by date (${o.shipByDate})`, detail: 'Pack it and enter the tracking number, or tell the customer about the delay.', action: link });
      }
      if (o.shipCountry && o.shipCountry.toUpperCase() !== 'US') {
        out['shipping-processing'].push({ agent: 'shipping-processing', severity: 'low', dedupeKey: `desk:customs:${o.id}`, title: `${o.orderNumber} ships to ${o.shipCountry.toUpperCase()}: prepare customs documents`, detail: 'Create a shipment file so the customs team can prepare the paperwork.', action: { type: 'link', href: '/dashboard/shipments' } });
      }
    } else if (o.status === 'shipped' && o.shippedAt && now.getTime() - o.shippedAt.getTime() > 7 * DAY) {
      out['shipping-processing'].push({ agent: 'shipping-processing', severity: 'medium', dedupeKey: `desk:transit:${o.id}`, title: `${o.orderNumber} shipped ${Math.floor((now.getTime() - o.shippedAt.getTime()) / DAY)} days ago and is not marked delivered`, detail: `Check tracking${o.trackingNo ? ` ${o.trackingNo}` : ''} with ${o.carrier ?? 'the carrier'}.`, action: link });
    }
  }
  for (const m of msgs) {
    out['customer-service'].push({
      agent: 'customer-service',
      severity: m.status === 'escalated' ? 'high' : 'medium',
      dedupeKey: `desk:msg:${m.id}`,
      title: `${m.status === 'escalated' ? 'Escalated' : 'Reply to approve'}: ${m.subject ?? m.fromEmail}`,
      detail: m.escalationReason ?? 'Waiting for a person.',
      action: link,
    });
  }
  return out;
}

// ---- The desk run ---------------------------------------------------------

/** Runs the four desk agents in order. Safe to call often and from several places at once. */
export async function runDesk(opts: { now?: Date; llm?: LlmClient } = {}): Promise<DeskRunSummary[]> {
  const db = getDb();
  const now = opts.now ?? new Date();
  const deps: Deps = { now, llm: opts.llm, useLlm: llmEnabled() || !!opts.llm };

  // A crashed run can leave rows claimed; hand them back.
  const cutoff = new Date(now.getTime() - STUCK_MS);
  await db.update(orders).set({ status: 'received' }).where(and(eq(orders.status, 'parsing'), lt(orders.updatedAt, cutoff)));
  await db.update(serviceMessages).set({ status: 'open' }).where(and(eq(serviceMessages.status, 'handling'), lt(serviceMessages.updatedAt, cutoff)));

  const steps: [DeskAgentId, (d: Deps) => Promise<number>][] = [
    ['order-intake', runIntake],
    ['customer-service', runService],
    ['order-processing', runProcessing],
    ['shipping-processing', runShipping],
  ];
  const summaries: DeskRunSummary[] = [];
  for (const [agent, fn] of steps) {
    const [run] = await db.insert(agentRuns).values({ agent }).returning();
    try {
      const handled = await fn(deps);
      await db.update(agentRuns).set({ finishedAt: new Date(), findingsCount: handled }).where(eq(agentRuns.id, run.id));
      summaries.push({ agent, handled });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      await db.update(agentRuns).set({ finishedAt: new Date(), error: message }).where(eq(agentRuns.id, run.id));
      summaries.push({ agent, handled: 0, error: message });
    }
  }

  const findings = await deskFindings(now);
  for (const meta of DESK_AGENTS) await persistFindings(meta.id, findings[meta.id]);
  return summaries;
}
